# Use root/example as user/password credentials
version: '3.1'

volumes:
   mongo-data:
      external: true

services:
   mongo:
      image: mongo
      restart: always
      container_name: mongodb-container
      ports:
         - "27017-27019:27017-27019"
      environment:
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: password
      volumes:
         - mongo-data:/data/db
